#!/usr/bin/env python3
# The notices an end-to-end message carries under the signature, from the
# mail repository (server/domains/<domain>/footer-e2e.txt, then footer.txt),
# for notices.mjs. The reader writes them itself: the mail server hands the
# composer only the signature, so it cannot put words of its own into the
# notice that tells a recipient how the message was protected.
# MAIL_REPO: the mail repository (default ~/Desktop/Projects/mail).
import json, os

here = os.path.dirname(os.path.abspath(__file__))
src = os.path.join(os.environ.get("MAIL_REPO") or os.path.expanduser("~/Desktop/Projects/mail"), "server", "domains")


def text(path):
    try:
        with open(path) as f:
            return " ".join(f.read().split())
    except OSError:
        return ""


notices = {}
for domain in sorted(os.listdir(src)):
    sealed, notice = text(os.path.join(src, domain, "footer-e2e.txt")), text(os.path.join(src, domain, "footer.txt"))
    if sealed or notice:
        notices[domain] = {"sealed": sealed, "notice": notice}
with open(os.path.join(here, "notices.mjs"), "w") as f:
    f.write("// Generated by make-notices.py from the mail repository: the notices under\n"
            "// the signature of an end-to-end message, by the sender's domain. The\n"
            "// end-to-end one first, the domain's own notice last.\n"
            "export const NOTICES = " + json.dumps(notices, indent=1, ensure_ascii=False) + ";\n")
print(f"make-notices: {len(notices)} domains")
