// Generated by make-notices.py from the mail repository: the notices under
// the signature of an end-to-end message, by the sender's domain. The
// end-to-end one first, the domain's own notice last.
export const NOTICES = {
 "dzyza.com": {
  "sealed": "We're writing end to end: only you and I can read this, our mail servers can't. Let's keep it that way: reply from here, and look for the lock. If it's ever missing on a message from me, tell me before you send anything private.",
  "notice": "This email is meant only for the people it's addressed to. If it reached you by mistake, please tell me and delete it, and don't forward or use what's in it."
 },
 "legalmachines.org": {
  "sealed": "END-TO-END ENCRYPTED: This message was encrypted on the sender's device and can be read only by its named recipients, not by the mail servers of either side. Please reply from the same app so that your reply is encrypted too. If a message in this thread arrives unencrypted (your app shows no lock), do not reply with confidential information, and notify the sender.",
  "notice": "CONFIDENTIALITY NOTICE: This email and any attachments are intended only for the named recipient(s) and may contain confidential or legally privileged information. If you received it in error, please notify the sender by reply and delete the message and any copies. Any other review, use, disclosure, copying or distribution is prohibited. Delivery to an unintended recipient does not waive confidentiality or privilege."
 }
};
